FROM apache/airflow:2.7.1-python3.11

USER root

# Install dependencies
RUN apt-get update && \
    apt-get install -y gcc python3-dev procps && \
    apt-get clean

# Install the latest OpenJDK
RUN apt-get install -y openjdk-17-jdk && \
    apt-get clean

# Set JAVA_HOME environment variable
#ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-arm64

# Update the PATH to include the correct Java binaries
ENV PATH $PATH:$JAVA_HOME/bin

USER airflow

# Install pip requirements
RUN pip install apache-airflow pyspark apache-airflow-providers-apache-spark apache-airflow-providers-google apache-airflow-providers-http