version: '3.7'

networks:
  airflow: {}

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: dockerfile_airflow
  env_file:
    - airflow.env
  volumes:
    - ./jobs:/opt/airflow/jobs
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./data:/opt/airflow/data
  depends_on:
    - postgres
  networks:
    - airflow

services:

  postgres:
    container_name: airflow-postgres
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: >
      bash -c "while ! pg_isready -h postgres -U airflow; do echo waiting for postgres; sleep 2; done;
      airflow db init || true;
      airflow webserver"
    ports:
      - "8080:8080"

  scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: >
      bash -c "while ! pg_isready -h postgres -U airflow; do echo waiting for postgres; sleep 2; done;
      airflow db migrate &&
      airflow users create --username admin --firstname E --lastname Y --role Admin --email 123@123.com --password airflow &&
      airflow scheduler"
